### ISSUE TITLE
ERR_INVALID_URL - Release 1.3.3 error

### ISSUE THREAD

**Issue by tapankumar** [ozantunca/elb-log-analyzer#251]
Hi,

Release 1.3.3 is giving below error while 1.3.2 is working fine with my elb logs.

elb-log-analyzer ~/tmp/ --col1=count --col2=requested_resource --col3=elb_status_code --prefix3=404 --limit=100
internal/url.js:257
  throw new ERR_INVALID_URL(input);
  ^

TypeError [ERR_INVALID_URL]: Invalid URL: http://x.x.x.x:80-
    at onParseError (internal/url.js:257:9)
    at parse (<anonymous>)
    at new URL (internal/url.js:333:5)
    at Object.parseLine (/xx/.nvm/versions/node/v12.18.1/lib/node_modules/elb-log-analyzer/dist/utils/parseLine.js:15:23)
    at Object.process (/xx/.nvm/versions/node/v12.18.1/lib/node_modules/elb-log-analyzer/dist/utils/generateProcessor.js:39:56)
    at Interface.<anonymous> (/xx/.nvm/versions/node/v12.18.1/lib/node_modules/elb-log-analyzer/dist/utils/parseAndProcessFiles.js:19:9)
    at Interface.emit (events.js:315:20)
    at Interface._onLine (readline.js:329:10)
    at Interface._normalWrite (readline.js:474:12)
    at ReadStream.ondata (readline.js:186:10) {
  input: 'http://x.x.x.x:80-',
  code: 'ERR_INVALID_URL'
}

**Comment by ozantunca** [comment]
Hey there @tapankumar . I couldn't reproduce this. Could you send the exact URL that's failing?

**Comment by ping86** [comment]
09:58 $ elb-log-analyzer *
internal/url.js:243
  throw error;
  ^

Same issue

```
TypeError [ERR_INVALID_URL]: Invalid URL: http://mycustombalancerr-11123456678.eu-west-1.elb.amazonaws.com:80-
    at onParseError (internal/url.js:241:17)
    at new URL (internal/url.js:319:5)
    at Object.parseLine (/usr/lib/node_modules/elb-log-analyzer/dist/utils/parseLine.js:16:23)
    at Object.process (/usr/lib/node_modules/elb-log-analyzer/dist/utils/generateProcessor.js:39:56)
    at Interface.RL.on (/usr/lib/node_modules/elb-log-analyzer/dist/utils/parseAndProcessFiles.js:19:9)
    at Interface.emit (events.js:189:13)
    at Interface._onLine (readline.js:290:10)
    at Interface._normalWrite (readline.js:433:12)
    at ReadStream.ondata (readline.js:149:10)
    at ReadStream.emit (events.js:189:13)
```

**Comment by DRTorrontegi** [comment]
Same issue here

internal/url.js:221
  throw error;
  ^

TypeError [ERR_INVALID_URL]: Invalid URL: http://integradorlb-149218599.eu-west-3.elb.amazonaws.com:443-
    at onParseError (internal/url.js:219:17)
    at parse (internal/url.js:228:3)
    at new URL (internal/url.js:311:5)
    at Object.parseLine (/usr/local/lib/node_modules/elb-log-analyzer/dist/utils/parseLine.js:16:23)
    at Object.process (/usr/local/lib/node_modules/elb-log-analyzer/dist/utils/generateProcessor.js:39:56)
    at Interface.RL.on (/usr/local/lib/node_modules/elb-log-analyzer/dist/utils/parseAndProcessFiles.js:19:9)
    at emitOne (events.js:116:13)
    at Interface.emit (events.js:211:7)
    at Interface._onLine (readline.js:282:10)
    at Interface._normalWrite (readline.js:424:12)

**Comment by DRTorrontegi** [comment]
Hi another error

internal/url.js:221
  throw error;
  ^

TypeError [ERR_INVALID_URL]: Invalid URL: undefined
    at onParseError (internal/url.js:219:17)
    at parse (internal/url.js:228:3)
    at new URL (internal/url.js:311:5)
    at Object.parseLine (/usr/local/lib/node_modules/elb-log-analyzer/dist/utils/parseLine.js:16:23)
    at Object.process (/usr/local/lib/node_modules/elb-log-analyzer/dist/utils/generateProcessor.js:39:56)
    at Interface.RL.on (/usr/local/lib/node_modules/elb-log-analyzer/dist/utils/parseAndProcessFiles.js:19:9)
    at emitOne (events.js:116:13)
    at Interface.emit (events.js:211:7)
    at ReadStream.onend (readline.js:147:12)
    at emitNone (events.js:111:20)
