### ISSUE TITLE
babel-polyfill dependency not installing

### ISSUE THREAD

**Issue by guillaumemolter** [ozantunca/elb-log-analyzer#4]
I installed using `npm install -g elb-log-analyzer`.

Result : 
```
└─┬ elb-log-analyzer@0.3.0
  ├── async@1.5.2
  ├── bluebird@3.3.3
  ├── colors@1.1.2
  ├─┬ glob@5.0.15
  │ ├─┬ inflight@1.0.4
  │ │ └── wrappy@1.0.1
  │ ├── inherits@2.0.1
  │ ├─┬ minimatch@3.0.0
  │ │ └─┬ brace-expansion@1.1.3
  │ │   ├── balanced-match@0.3.0
  │ │   └── concat-map@0.0.1
  │ ├── once@1.3.3
  │ └── path-is-absolute@1.0.0
  ├─┬ optimist@0.6.1
  │ ├── minimist@0.0.10
  │ └── wordwrap@0.0.3
  └── underscore@1.8.3
```

When I was trying to use `elb-log-analyzer` I was getting the following error message:
```
Error: Cannot find module 'babel-polyfill'
    at Function.Module._resolveFilename (module.js:339:15)
    at Function.Module._load (module.js:290:25)
    at Module.require (module.js:367:17)
    at require (internal/module.js:16:19)
    at Object.<anonymous> (/usr/local/lib/node_modules/elb-log-analyzer/cli.js:7:1)
    at Module._compile (module.js:413:34)
    at Object.Module._extensions..js (module.js:422:10)
    at Module.load (module.js:357:32)
    at Function.Module._load (module.js:314:12)
    at Function.Module.runMain (module.js:447:10)
```

After manually installing `npm install -g babel-polyfill` `elb-log-analyzer` works great.

Not 100% if it's a compilation/packaging problem, or a missing dependency.

**Comment by ozantunca** [comment]
Thanks for noticing such a critical error. I have used a newer version of `babel-polyfill` so used that instead of yours. Thank you for your contribution. The error should be fixed once you update `elb-log-analyzer`.
